# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Data Model"
  url = "#dom"
  weight = 20
  identifier = "dom-id"

[[main]]
  name = "About"
  url = "#dom-about"
  weight = 5
  parent = "dom-id"

[[main]]
  name = "Specification"
  url = "#dom-about"
  weight = 10
  parent = "dom-id"

[[main]]
  name = "Libraries"
  url = "#dom-about"
  weight = 15
  parent = "dom-id"

[[main]]
  name = "Ontology"
  url = "#dom-about"
  weight = 20
  parent = "dom-id"

[[main]]
  name = "Converter"
  url = "#dom-about"
  weight = 25
  parent = "dom-id"

[[main]]
  name = "Validator"
  url = "#dom-about"
  weight = 30
  parent = "dom-id"

[[main]]
  name = "Examples"
  url = "#dom-about"
  weight = 35
  parent = "dom-id"

[[main]]
  name = "Visual"
  url = "/visual-about"
  weight = 25
  identifier = "visual-id"

[[main]]
  name = "About SBOL Visual"
  url = "/visual-about"
  weight = 5
  parent = "visual-id"

[[main]]
  name = "SBOL Visual Specification"
  url = "/visual-specification"
  weight = 10
  parent = "visual-id"

[[main]]
  name = "Glyphs"
  url = "/visual-glyphs"
  weight = 15
  parent = "visual-id"

[[main]]
  name = "Ontology"
  url = "/visual-ontology"
  weight = 20
  parent = "visual-id"

[[main]]
  name = "SBOL Visual Examples"
  url = "/visual-examples"
  weight = 25
  parent = "visual-id"

[[main]]
  name = "Applications"
  url = "/applications"
  weight = 30

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40

[[main]]
  name = "Community"
  url = "/community"
  weight = 50
  identifier = "community-id"

[[main]]
  name = "About"
  url = "/community"
  weight = 5
  parent = "community-id"

[[main]]
  name = "Meetings"
  url = "/community-meetings"
  weight = 10
  parent = "community-id"

[[main]]
  name = "Outreach"
  url = "/community-outreach"
  weight = 15
  parent = "community-id"

[[main]]
  name = "Governance"
  url = "/community-governance"
  weight = 20
  parent = "community-id"

[[main]]
  name = "SBOL Industrial Consortium"
  url = "/sbol-industrial"
  weight = 25
  parent = "community-id"

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 55

[[main]]
  name = "FAQ"
  url = "/faq"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
